### ISSUE TITLE
Implementation of RobustWindowScope

### ISSUE THREAD

**Issue by drauch** [featurist/coypu#129]
In case the current window is somehow stale, the `RobustWindowScope` tries to requery the window via its `WindowFinder`. This may not be the best behavior - especially if the page has changed its title in the meantime.

A better way would be to save the Selenium window identifier after the first successful query of the window and use that in every following call?

Why bother to re-"find" the window each time? As I said, this has the disadvantage of failing whenever the window title changed in the meantime...

Best regards,
Dominik

**Comment by adiel** [comment]
Yep. It's just a little more complicated than that because we have to ensure that we switch to the correct window (if you have used a different scope in the meantime), which is probably why it's like it is historically. But I do agree this behaviour would be preferable and it should be much easier to implement since ec3db89.

**Comment by adiel** [comment]
Hi. I've checked and double checked this, and while I found some redundant code which was a bit confusing, the Find Window is definitely not being called every time. It does appear that way when you look at RobustWindowScope, but lower down it then does a stale element check which saves it from re-finding unless the window has become stale or you find the element again.

I tried to recreate your problem by finding a pop up window, changing the title of the pop up, and then interacting with the pop up and the original window again, but this test passes fine, I only see a failure to find the window when I look for the window again with a fresh call to browserSession.FindWindow().

The only explanation I have for what you are seeing is that you have maybe not yet interacted with the window at all at the point at which the title changes in your page.

Because of the deferred execution of finders in coypu you may have done this coincidentally by doing something like:

```c#
browserSession.ClickLink("Open popup");
var popUp = browserSession.FindWindow("My Pop Up");

browserSession.ClickLink("Something that changes the title of the pop up");

popUp.ClickLink("A link in the pop up");
```

This would fail becase it is only when you actually do something in a scope, such as look for content, assert the existance of an element, click something, etc that the finder first executes.

Could this be your problem? Cant think of any other possibility.

You could work around this by adding `Assert.That(popUp.Exists());` immediately after `browserSession.FindWindow(...)`

Incidentally I am thinking of making a breaking change to immediately execute every finder when the scope is first created. This is how Capybara works and while I did have a reason for doing it this way, I think it's a little surprising all round and it should probably be changed. You have an opinion on that?

Shouln't affect too many existing tests unless someone has code like my example from the readme:

```c#

var advancedSearch = browser.FindFieldset("Advanced search");
var searchResults = browser.FindSection("Search results");

advancedSearch.FillIn("First name").With("Philip");
advancedSearch.FillIn("Middle initial").With("J");
advancedSearch.FillIn("Last name").With("Fry");

advancedSearch.Click("Find");

Assert.That(searchResults, Shows.Content("1 friend found"));
```

Which would start to fail if the search results section doesn't appear until after you submit the form. But I think the current behaviour is pretty surprising so I do think I will change it in the next version.

**Comment by drauch** [comment]
(1) My current setup is the following:

1. Page A: click on link which eventually opens the new window (it is an ASP.NET page, so first a postback to the same page is executed, the response contains JavaScript opening the popup...)
2. The new window has the title TitleABC & is found
3. I click a link on the window (another postback), the response changes the title to TitleDEF
4. I am trying to read `windowRootElementScope.FindCss ("title").InnerHTML` which fails with the message that the title TitleABC is not found:

Coypu.MissingWindowException : Unable to find window: TitleABC
   at Coypu.Timing.RetryUntilTimeoutTimingStrategy.Synchronise[TResult](Query`1 query)
   at Coypu.DriverScope.Query[T](Query`1 query)
   at Coypu.SynchronisedElementScope.Try[T](Func`1 getAttribute)
   at Coypu.ElementScope.get_InnerHTML()

**Comment by adiel** [comment]
I assume you are on the latest Coypu?

Any chance you can post the exact test code?

**Comment by drauch** [comment]
(1) Yes, latest Coypu, unfortunately, I cannot post the "real" code. I have also tried to reproduce it, but haven't been successful yet. It happens roughly 1 in 10 times only in the original code :-/

I'm going to inform you as soon as I've found out more.

(2)
1. Doesn't that make all scope.FindCss("...").Exists() queries impossible?
2. Also, I'm sometimes caching those selectors over multiple requests, as soon as it hits a StaleElementException it should re-find it - does that still happen if you immediately Now() the query?
3. Also I'm often combining queries (due to representing pages, controls, etc. with own objects). Therefore I often have stuff like scope.Find(...).Find(...).Find(...) - I assume there is no performance change when automatically Now()'ing the query?

**Comment by adiel** [comment]
On Tue, Jan 27, 2015 at 10:42 AM, drauch <notifications@github.com> wrote:

> (1) Yes, latest Coypu, unfortunately, I cannot post the "real" code. I
> have also tried to reproduce it, but haven't been successful yet. It
> happens roughly 1 in 10 times only in the original code :-/
>
ok, that's interesting..

> I'm going to inform you as soon as I've found out more.
>
Cheers, happy to take another look at that point

> (2)
> 1. Doesn't that make all scope.FindCss("...").Exists() queries impossible?
>
 .Exists() will cause the finder to execute (i.e. calls Now())

> 2. Also, I'm sometimes caching those selectors over multiple requests, as
> soon as it hits a StaleElementException it should re-find it - does that
> still happen if you immediately Now() the query?
>
Yes

**Comment by drauch** [comment]
> .Exists() will cause the finder to execute (i.e. calls Now())

I was thinking more about code like this:

    if(!scope.FindCss("...").Exists(Options.NoWait))
        // do something

Would be a problem if `FindCss()` calls `Now()` internally, wouldn't it?

> Cheers, happy to take another look at that point

Thanks for your effort! Really like your project and your helpfulness! :-)

**Comment by adiel** [comment]
On Tue, Jan 27, 2015 at 12:47 PM, drauch <notifications@github.com> wrote:

> .Exists() will cause the finder to execute (i.e. calls Now())
>
> I was thinking more about code like this:
>
> if(!scope.FindCss("...").Exists(Options.NoWait))
>     // do something
>
> Would be a problem if FindCss() calls Now() internally, wouldn't it?
>

Yes, I see your point. Exists/Missing would need a different solution.
Capybara has:

scope.has_css("...") etc (which coypu used to have but I got rid of in
favour of exists / missing.

Would need to address all this for sure. But I might have a go and see how
it comes out.
Thanks!

>  Cheers, happy to take another look at that point
>
> Thanks for your effort! Really like your project and your helpfulness! :-)
>
Sure thing

**Comment by drauch** [comment]
I like Exists/Missing more - especially, as my layered approach does not work without it. I have a page object, it owns some control objects, which can have children, etc.

A child retrieves an outer scope from its parent, e.g.:

Page scope = window.FindCss("html");
Control scope = parentScope.FindCss("#myControl1");
Child scope = parentScope.FindXPath("div.listMenu");
etc.

If I want to check within the child control object if the listMenu exists, I can simply call .Exists() - would not work at all with the direct approach.

So probably it would be a good idea to add the "immediate query" as a possiblity to the Options? You could have a default like "AlwaysQueryImmediately" or "NeverQueryImmediately" and could overwrite it for specific queries?
