### ISSUE TITLE
Project Activity

### ISSUE THREAD

**Issue by sbowler** [featurist/coypu#182]
Is this project dead? There seems to be little activity for some time. Is there another similar project or fork that is better maintained that someone would recommend? 

We are looking at using this, but am a little concerned about the lack of updates. Any information is appreciated.

**Comment by obstar** [comment]
Project is a bit rusty ;)  some dependencies should be updated it to newest versions (in the company I work currently we do this internally because we got other dependencies so we have a bit custom version of coypu) other then that all is good. I guess if project want to survive the work on v3 with support of .net core should be resume and finished, not even to mention to extend it this framework to support mobile browsers and appium integration.
Anyway at the moment there is lack of time and people willing to do that job for free.

**Comment by brigs** [comment]
@obstar thanks for the info! Is there a an overview of what's needed to move forward anywhere (except for what you mentioned) ? I'd be happy to help out

**Comment by obstar** [comment]
project is back on track, new release soon
